version: '3.8'

services:
  backend:
    build: .
    container_name: customer-service-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://database:5432/spring_be
      JWT_SECRET_KEY: your_jwt_key
    depends_on:
      - database

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring_be
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


#services:
#  backend:
#    build: .
#    container_name: customer-service-api
#    ports:
#      - "8080:8888"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD:
#      POSTGRES_URL: jdbc:postgresql://host.docker.internal:5432/spring_be
#      JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
##    depends_on:
##      - database
#
##  database:
##    image: postgres:16.0
##    environment:
##      POSTGRES_USER: dbuser
##      POSTGRES_PASSWORD: dbpass
##      POSTGRES_DB: dbname
##    volumes:
##      - pgdata:/var/lib/postgresql/data
##
##volumes:
##  pgdata: